export const UPDATE_PET = "UPDATE_PET"
export const UPDATE_PET_SUCCEEDED = "UPDATE_PET_SUCCEEDED"
export const UPDATE_PET_FAILED = "UPDATE_PET_FAILED"
export const ADD_PET = "ADD_PET"
export const ADD_PET_SUCCEEDED = "ADD_PET_SUCCEEDED"
export const ADD_PET_FAILED = "ADD_PET_FAILED"
export const FIND_PETS_BY_STATUS = "FIND_PETS_BY_STATUS"
export const FIND_PETS_BY_STATUS_SUCCEEDED = "FIND_PETS_BY_STATUS_SUCCEEDED"
export const FIND_PETS_BY_STATUS_FAILED = "FIND_PETS_BY_STATUS_FAILED"
export const FIND_PETS_BY_TAGS = "FIND_PETS_BY_TAGS"
export const FIND_PETS_BY_TAGS_SUCCEEDED = "FIND_PETS_BY_TAGS_SUCCEEDED"
export const FIND_PETS_BY_TAGS_FAILED = "FIND_PETS_BY_TAGS_FAILED"
export const GET_PET_BY_ID = "GET_PET_BY_ID"
export const GET_PET_BY_ID_SUCCEEDED = "GET_PET_BY_ID_SUCCEEDED"
export const GET_PET_BY_ID_FAILED = "GET_PET_BY_ID_FAILED"
export const UPDATE_PET_WITH_FORM = "UPDATE_PET_WITH_FORM"
export const UPDATE_PET_WITH_FORM_SUCCEEDED = "UPDATE_PET_WITH_FORM_SUCCEEDED"
export const UPDATE_PET_WITH_FORM_FAILED = "UPDATE_PET_WITH_FORM_FAILED"
export const DELETE_PET = "DELETE_PET"
export const DELETE_PET_SUCCEEDED = "DELETE_PET_SUCCEEDED"
export const DELETE_PET_FAILED = "DELETE_PET_FAILED"
export const UPLOAD_FILE = "UPLOAD_FILE"
export const UPLOAD_FILE_SUCCEEDED = "UPLOAD_FILE_SUCCEEDED"
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED"
export const GET_INVENTORY = "GET_INVENTORY"
export const GET_INVENTORY_SUCCEEDED = "GET_INVENTORY_SUCCEEDED"
export const GET_INVENTORY_FAILED = "GET_INVENTORY_FAILED"
export const PLACE_ORDER = "PLACE_ORDER"
export const PLACE_ORDER_SUCCEEDED = "PLACE_ORDER_SUCCEEDED"
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED"
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID"
export const GET_ORDER_BY_ID_SUCCEEDED = "GET_ORDER_BY_ID_SUCCEEDED"
export const GET_ORDER_BY_ID_FAILED = "GET_ORDER_BY_ID_FAILED"
export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_SUCCEEDED = "DELETE_ORDER_SUCCEEDED"
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED"
export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_SUCCEEDED = "CREATE_USER_SUCCEEDED"
export const CREATE_USER_FAILED = "CREATE_USER_FAILED"
export const CREATE_USERS_WITH_ARRAY_INPUT = "CREATE_USERS_WITH_ARRAY_INPUT"
export const CREATE_USERS_WITH_ARRAY_INPUT_SUCCEEDED =
  "CREATE_USERS_WITH_ARRAY_INPUT_SUCCEEDED"
export const CREATE_USERS_WITH_ARRAY_INPUT_FAILED =
  "CREATE_USERS_WITH_ARRAY_INPUT_FAILED"
export const CREATE_USERS_WITH_LIST_INPUT = "CREATE_USERS_WITH_LIST_INPUT"
export const CREATE_USERS_WITH_LIST_INPUT_SUCCEEDED =
  "CREATE_USERS_WITH_LIST_INPUT_SUCCEEDED"
export const CREATE_USERS_WITH_LIST_INPUT_FAILED =
  "CREATE_USERS_WITH_LIST_INPUT_FAILED"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED"
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED"
export const GET_USER_BY_NAME = "GET_USER_BY_NAME"
export const GET_USER_BY_NAME_SUCCEEDED = "GET_USER_BY_NAME_SUCCEEDED"
export const GET_USER_BY_NAME_FAILED = "GET_USER_BY_NAME_FAILED"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCEEDED = "UPDATE_USER_SUCCEEDED"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCEEDED = "DELETE_USER_SUCCEEDED"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"

export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
